# yaml-language-server: $schema=https://raw.githubusercontent.com/buildkite/pipeline-schema/main/schema.json

env:
  SETUP_GVM_VERSION: 'v0.5.2'
  LINUX_AGENT_IMAGE: "golang:${GO_VERSION}"
  WINDOWS_AGENT_IMAGE: "family/core-windows-2022"

steps:
  - label: ":golangci-lint: Lint"
    key: lint-test
    command: ".buildkite/scripts/lint_test.sh"
    agents:
      image: "${LINUX_AGENT_IMAGE}"
      cpu: "8"
      memory: "4G"

  - label: "Container-System tests; Rhel 9"
    key: linux-container-test-rhel9
    command: ".buildkite/scripts/system-container-tests.sh"
    agents:
      image: "family/platform-ingest-beats-rhel-9"
      provider: "gcp"
      cpu: "8"
      memory: "4G"

  - label: "Container-System tests; Old Ubuntu"
    key: linux-container-test-u2004
    command: ".buildkite/scripts/system-container-tests.sh"
    agents:
      image: "family/platform-ingest-beats-ubuntu-2004"
      provider: "gcp"
      cpu: "8"
      memory: "4G"

  - label: "Container-System tests"
    key: linux-container-test
    command: ".buildkite/scripts/system-container-tests.sh"
    agents:
      image: "family/platform-ingest-beats-ubuntu-2204"
      provider: "gcp"
      cpu: "8"
      memory: "4G"

  - label: ":linux: Tests on Linux"
    key: linux-test
    command: ".buildkite/scripts/run-linux-tests.sh"
    agents:
      image: "${LINUX_AGENT_IMAGE}"
      cpu: "8"
      memory: "4G"
    artifact_paths: "*.xml"

  - label: ":windows: Tests on Windows"
    key: windows-test
    command: ".buildkite/scripts/run-win-tests.ps1"
    agents:
      provider: "gcp"
      image: "${WINDOWS_AGENT_IMAGE}"
    artifact_paths: "*.xml"

  - label: ":linux: Tests on MacOS"
    key: macos-test
    command: ".buildkite/scripts/run-linux-tests.sh junit-mac-report.xml"
    agents:
      provider: "orka"
      imagePrefix: generic-13-ventura-arm
    artifact_paths: "*.xml"

  - label: ":junit: Junit annotate"
    plugins:
      - junit-annotate#v2.4.1:
          artifacts: "*.xml"
          fail-build-on-error: true
    agents:
      provider: "gcp"
    depends_on:
      - step: "linux-test"
        allow_failure: true
      - step: "windows-test"
        allow_failure: true
      - step: "macos-test"
        allow_failure: true
